spring:
  application:
    name: gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: payment
            uri: lb://payment
            predicates:
              - Path=/api/payment/**

          - id: order
            uri: lb://order
            predicates:
              - Path=/api/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

server:
  port: 19091

